services:
  postgres:
    image: postgres:15-alpine
    container_name: hris_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hris_db
    ports:
      - '5431:5432'
    volumes:
      - hris_data:/var/lib/postgresql/data

volumes:
  hris_data:
